### ISSUE TITLE
All relative links to bitsrc.io in the documentation are broken

### ISSUE THREAD

**Issue by alesanchezr** [teambit/bit-docs#18]
For example, the authentication issues page took me to this 404:
https://docs.bitsrc.io/docs/bitsrc.io/settings/profile

I already did the pull request for that URL but I think there are several like this one.

**Comment by itaymendel** [comment]
It appears that some of the external links where missing `https://`.
Grepped for all the bad references, and fixed all.

Thanks for submitting the issue :)
