### ISSUE TITLE
misunderstanding between angular-guidelines and cli-all 

### ISSUE THREAD

**Issue by rbalet** [teambit/bit-docs#37]
I tried *[Tracking a component for each sub-directory, and setting the main file dynamically*](https://docs.bit.dev/docs/apis/cli-all#add) liek that for an angular project but it doens't worked.
```ts
bit add src/app/components/**/ --main '{PARENT}.module.ts'

// output
error: the component anim-icon does not contain a main file.
please either use --id to group all added files as one component or use our DSL to define the main file dynamically.
see troubleshooting at https://docs.bit.dev/docs/isolating-and-tracking-components.html#define-a-components-main-file
```
I then had to read the [angular guidelines](https://docs.bit.dev/docs/angular-guidelines#specify-the-modulets-file-as-the-component-entry-point)

the first is like that
```ts
// cli-all
bit add src/**/ --main '{PARENT}.js'
```
and the second
```ts
bit add src/app/components/*/ --main 'src/app/components/{PARENT}/{PARENT}.module.ts'
```

Why does the first solution I wrote not worked? is that because of the *.module*.ts? if it's the case, a small docs update could be helpfull :)

**Comment by Tallyb** [comment]
Hi, 
As per the error, it seems that the . `anim-icon` does not have a anim-icon.module.ts file. Is this the case? 
Our recommendation for Angular components is to have a module for each component. This ensure a consistent context for compilation. 
If you feel anything else is missing let me know, or simply suggest an edit on the docs themselves.

**Comment by rbalet** [comment]
He had the anim-icon.module.ts and I've controlled it. I have the feeling that the all-cli isn't working for files with `something.type.ts`. I'll do the change in the doc and make a pull request :)
