### ISSUE TITLE
Bad anchor link for importing-components#link-components

### ISSUE THREAD

**Issue by kcampion** [teambit/bit-docs#8]
From https://docs.bitsrc.io/docs/importing-components.html, this sentence `To require this component you can use either relative paths or absolute paths see Linking components section.`, the link to `Linking components` has a bad anchor

`https://docs.bitsrc.io/docs/importing-components.html#linking-components`
instead of
`https://docs.bitsrc.io/docs/importing-components.html#link-components`

**Comment by itaymendel** [comment]
fixed. thanks for noticing!
